#!/bin/bash
#Build source descriptor
debuild -us -uc -S 

#Lucid
sudo rm -rf /var/cache/pbuilder/result/*
sudo pbuilder build ../*.dsc 

mkdir -p ../packages/dists
mkdir -p ../packages/dists/lucid
mkdir -p ../packages/dists/lucid/universe
mkdir -p ../packages/dists/lucid/universe/binary-i386
sudo rm -f ../packages/dists/lucid/universe/binary-i386/*

cp /var/cache/pbuilder/result/dwarftherapist*.deb ../packages/dists/lucid/universe/binary-i386

#Other dists in pbuilder (TODO: move lucid here)
for dist in "maverick" "sid" "lenny"
do
	sudo rm -rf ~/pbuilder/${dist}_result/*
	sudo pbuilder-dist $dist build ../*.dsc 

	mkdir -p ../packages/dists
	mkdir -p ../packages/dists/$dist
	mkdir -p ../packages/dists/$dist/universe
	mkdir -p ../packages/dists/$dist/universe/binary-i386
	sudo rm -f ../packages/dists/$dist/universe/binary-i386/*

	cp ~/pbuilder/${dist}_result/dwarftherapist*.deb ../packages/dists/$dist/universe/binary-i386
done


# Build repository
pushd ..
./build_repo
popd

