#!/bin/bash
debuild -us -uc -S 
sudo pbuilder-dist maverick build ../*.dsc 
mkdir -p ../packages/maverick
cp /home/ehlertjd/pbuilder/maverick_result/dwarftherapist_0.6.?_i386.deb ../packages/maverick
