#!/bin/sh
DT_VERSION=`cat inc/defines.h | awk 'BEGIN {i = 1} /#define DT_VERSION/ {ver[i++] = $3} END {printf("%d.%d.%d\n", ver[1], ver[2], ver[3])}'`

SRC_DIR=dwarftherapist-$DT_VERSION
TAR_FILE=../dwarftherapist-$DT_VERSION.tar.gz
TAR_FILE_ORIG=../dwarftherapist_$DT_VERSION.orig.tar.gz

rm -f $TAR_FILE

mkdir $SRC_DIR
cp default_gridviews.dtg $SRC_DIR
cp build_maverick $SRC_DIR
cp -R debian $SRC_DIR
cp -R dist $SRC_DIR
cp -R doc $SRC_DIR
cp dwarftherapist.pro $SRC_DIR
cp DwarfTherapist.rc $SRC_DIR
cp -R etc $SRC_DIR
cp hammer.ico $SRC_DIR
cp images.qrc $SRC_DIR
cp -R img $SRC_DIR
cp -R inc $SRC_DIR
cp LICENSE.txt $SRC_DIR/COPYRIGHT
cp README.txt $SRC_DIR/README
cp resource.h $SRC_DIR
cp -r src $SRC_DIR
cp -r thirdparty $SRC_DIR
cp -r ui $SRC_DIR

mkdir -p $SRC_DIR/bin
mkdir -p $SRC_DIR/bin/release

tar -czf $TAR_FILE $SRC_DIR
cp $TAR_FILE $TAR_FILE_ORIG
rm -rf $SRC_DIR


